/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contaaguateste;

import java.text.DecimalFormat;
import javax.swing.JLabel;
import static sun.security.krb5.Confounder.intValue;

/**
 *
 * @author Erick hayakawa
 */
public class teste2 extends javax.swing.JFrame {

    /**
     * Creates new form teste2
     */
    public teste2() {
        initComponents();
        
        //coloca tds os campos de digitação sem visibilidade para o usuario
        //Chuveiro
        chuveiro.setVisible(false);
        lblChuveiro.setVisible(false);
        //Descarga
        lbldescarga.setVisible(false);
        descarga.setVisible(false);
        //Pia do Banheiro
        lblpiaB.setVisible(false);
        piaBanheiro.setVisible(false);
        //maquina de lavar Roupa
        maquinaRoupa.setVisible(false);
        lblmaquiR.setVisible(false);
        //tanque
        lbltanque.setVisible(false);
        TanqueRoupa.setVisible(false);
        //maquina de lavar louça
        lblmaquiL.setVisible(false);
        maquinaLouca.setVisible(false);
        //pia da cozinha
        lblpiaC.setVisible(false);
        piaCozinha.setVisible(false);
    }

    // metodos para setar o valor enviado de litros para cada objeto
    public void setLbltotalM(String lbltotalM) {
        this.lbltotalM.setText(lbltotalM);
    }

    public void setLblTotal(String lblTotal) {
        this.lblTotal.setText(lblTotal);
    }

    public void setLblChuveiro(String lblChuveiro) {
        this.lblChuveiro.setText(lblChuveiro); 
    }

    public void setLbldescarga(String lbldescarga) {
        this.lbldescarga.setText(lbldescarga);
    }

    public void setLblmaquiL(String lblmaquiL) {
        this.lblmaquiL.setText(lblmaquiL);
    }

    public void setLblmaquiR(String lblmaquiR) {
        this.lblmaquiR.setText(lblmaquiR);
    }

    public void setLbltanque(String lbltanque) {
        this.lbltanque.setText(lbltanque);
    }

    public void setLblpiaB(String lblpiaB) {
        this.lblpiaB.setText(lblpiaB);
    }

    public void setLblpiaC(String lblpiaC) {
        this.lblpiaC.setText(lblpiaC);
    }
    
    //metodos utilizados para habilitar a visualização de um objeto ou a não visualização
    public void Chuv(){
        chuveiro.setVisible(true);
        lblChuveiro.setVisible(true);
    }
    public void Desc(){
        lbldescarga.setVisible(true);
        descarga.setVisible(true);
    }
    public void PiaBanho(){
        lblpiaB.setVisible(true);
        piaBanheiro.setVisible(true);
    }
    public void MaquiR(){
        maquinaRoupa.setVisible(true);
        lblmaquiR.setVisible(true);
    }
    public void Tanque(){
        lbltanque.setVisible(true);
        TanqueRoupa.setVisible(true);
    }
    public void MaquiL(){
        lblmaquiL.setVisible(true);
        maquinaLouca.setVisible(true);
    }
    public void PiaCoz(){
        lblpiaC.setVisible(true);
        piaCozinha.setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quantas = new javax.swing.JLabel();
        chuveiro = new javax.swing.JLabel();
        descarga = new javax.swing.JLabel();
        piaBanheiro = new javax.swing.JLabel();
        maquinaRoupa = new javax.swing.JLabel();
        TanqueRoupa = new javax.swing.JLabel();
        piaCozinha = new javax.swing.JLabel();
        maquinaLouca = new javax.swing.JLabel();
        Proximo = new javax.swing.JButton();
        lblChuveiro = new javax.swing.JLabel();
        lbldescarga = new javax.swing.JLabel();
        lblpiaB = new javax.swing.JLabel();
        lblmaquiR = new javax.swing.JLabel();
        lbltanque = new javax.swing.JLabel();
        lblpiaC = new javax.swing.JLabel();
        lblmaquiL = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        TotalM = new javax.swing.JLabel();
        lbltotalM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Quantas.setText("Total de agua gasta em Litros e M³");

        chuveiro.setText("Chuveiro");

        descarga.setText("Descarga");

        piaBanheiro.setText("lavar as mão");

        maquinaRoupa.setText("Maquina de lavar Roupa");

        TanqueRoupa.setText("Tanque de lavar");

        piaCozinha.setText("Pia da cozinha");

        maquinaLouca.setText("Maquina de lavar louça");

        Proximo.setText("Proximo");
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoActionPerformed(evt);
            }
        });

        Total.setText("TOTAL em Litros");

        TotalM.setText("TOTAL em M³");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(Proximo)
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descarga)
                            .addComponent(chuveiro)
                            .addComponent(piaBanheiro)
                            .addComponent(maquinaRoupa)
                            .addComponent(TanqueRoupa)
                            .addComponent(piaCozinha)
                            .addComponent(maquinaLouca)
                            .addComponent(Total)
                            .addComponent(TotalM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbltotalM, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(lblmaquiL, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(lblpiaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltanque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmaquiR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblpiaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChuveiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldescarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Quantas)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Quantas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(chuveiro)
                                                                    .addComponent(lblChuveiro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(descarga))
                                                            .addComponent(lbldescarga, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(piaBanheiro))
                                                    .addComponent(lblpiaB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(maquinaRoupa))
                                            .addComponent(lblmaquiR, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TanqueRoupa))
                                    .addComponent(lbltanque, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(piaCozinha))
                            .addComponent(lblpiaC, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maquinaLouca))
                    .addComponent(lblmaquiL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalM)
                    .addComponent(lbltotalM, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(Proximo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoActionPerformed
        DecimalFormat df = new DecimalFormat("#00.00");//deixa as variaveis double com apenas duas casas decimais
        
        teste3 form = new teste3();//instancia o Jframe3
        
        double metros;//variavel para controle dos metros no calculo da conta de agua
        
        metros = Math.round(Double.parseDouble(lbltotalM.getText()));//pega o valor passado no Jframe1 do total de M³
        
        form.setLblM3total(df.format(metros));//passa o valor total de m³ para o Jframe3
        
        double valor = 0.0;//cria a variavel para o calculo do valor em Reais
        
        if(metros <= 10){//se o m³ for menor ou igual a 10 o valor da conta é unico não precisa de conta
            valor = valor + 26.18;
        }else if(metros > 10){//se o m³ for maior que 10 é necessario retirar 10 do total de metros gastos e multiplicar o resto com a tarifa e adicionar a tarifa de 10M³
            
            metros = metros - 10;
            valor = valor + 26.18 + (metros*3.65);
            
        }else if(metros > 20){//se o m³ for maior que 20 é necessario retirar 20 do total de metros gastos e multiplicar o resto com a tarifa e adicionar a tarifa de 10M³ e da de 20M³
            
            metros = metros - 20;
            valor = valor + 26.18 + 36.5 + (metros*5.61);
            
        }else if(metros > 30){//se o m³ for maior que 30 é necessario retirar 30 do total de metros gastos e multiplicar o resto com a tarifae adicionar a tarifa de 10M³ e da de 20M³ e da de 30M³
            
            metros = metros - 30;
            valor = valor + 26.18 + 36.5 + 56.1 + (metros*5.61);   
            
        }else if(metros > 50){//se o m³ for maior que 50 é necessario retirar 50 do total de metros gastos e multiplicar o resto com a tarifae adicionar a tarifa de 10M³ e da de 20M³ e da de 30M³ e a de 50M³
            
            metros = metros - 50;
            valor = valor + 26.18 + 36.5 + 56.1 + 56.1 + (metros*6.71);
            
        }
        
        form.setLbltotalR(df.format(valor));//envia o valor em reais para o JFrame3
        form.setVisible(true);//deixa visivel o 3º JFrame
    }//GEN-LAST:event_ProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Proximo;
    private javax.swing.JLabel Quantas;
    private javax.swing.JLabel TanqueRoupa;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalM;
    private javax.swing.JLabel chuveiro;
    private javax.swing.JLabel descarga;
    private javax.swing.JLabel lblChuveiro;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lbldescarga;
    private javax.swing.JLabel lblmaquiL;
    private javax.swing.JLabel lblmaquiR;
    private javax.swing.JLabel lblpiaB;
    private javax.swing.JLabel lblpiaC;
    private javax.swing.JLabel lbltanque;
    private javax.swing.JLabel lbltotalM;
    private javax.swing.JLabel maquinaLouca;
    private javax.swing.JLabel maquinaRoupa;
    private javax.swing.JLabel piaBanheiro;
    private javax.swing.JLabel piaCozinha;
    // End of variables declaration//GEN-END:variables
}
