/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contaaguateste;

import java.text.DecimalFormat;
import javax.swing.JCheckBox;

/**
 *
 * @author Erick hayakawa
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
        //coloca tds os campos de digitação sem visibilidade para o usuario
        Ap.setVisible(false);
        Casa.setVisible(false);
        JTcasa.setVisible(false);
        lblCasa.setVisible(false);
        JTap.setVisible(false);
        lblAp.setVisible(false);
        JTmaquiL.setVisible(false);
        JTmaquiR.setVisible(false);
        JTpiaB.setVisible(false);
        JTpiaC.setVisible(false);
        JTprivada.setVisible(false);
        JTtanque.setVisible(false);
        lblCasa.setVisible(false);
        lblPiaB.setVisible(false);
        lblPiaC.setVisible(false);
        lblPrivada.setVisible(false);
        lblmaquiL.setVisible(false);
        lblmaquiR.setVisible(false);
        lbltanque.setVisible(false); 
        lblPessoas.setVisible(false);
        JSpessoas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Selecione = new javax.swing.JLabel();
        chuveiro = new javax.swing.JCheckBox();
        Descarga = new javax.swing.JCheckBox();
        PiaBanheiro = new javax.swing.JCheckBox();
        maquinaRoupa = new javax.swing.JCheckBox();
        tanqueRoupa = new javax.swing.JCheckBox();
        piaCozinha = new javax.swing.JCheckBox();
        maquinaLouca = new javax.swing.JCheckBox();
        Proximo = new javax.swing.JButton();
        JTcasa = new javax.swing.JTextField();
        JTprivada = new javax.swing.JSpinner();
        JTpiaB = new javax.swing.JTextField();
        JTmaquiR = new javax.swing.JSpinner();
        JTtanque = new javax.swing.JTextField();
        JTmaquiL = new javax.swing.JSpinner();
        JTpiaC = new javax.swing.JTextField();
        tempVez = new javax.swing.JLabel();
        lblCasa = new javax.swing.JLabel();
        lblPrivada = new javax.swing.JLabel();
        lblPiaB = new javax.swing.JLabel();
        lblmaquiR = new javax.swing.JLabel();
        lbltanque = new javax.swing.JLabel();
        lblPiaC = new javax.swing.JLabel();
        lblmaquiL = new javax.swing.JLabel();
        Casa = new javax.swing.JCheckBox();
        Ap = new javax.swing.JCheckBox();
        lblAp = new javax.swing.JLabel();
        JTap = new javax.swing.JTextField();
        lblPessoas = new javax.swing.JLabel();
        JSpessoas = new javax.swing.JSpinner();

        jLabel9.setText("jLabel9");

        jLabel1.setText("jLabel1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Selecione.setText("Selecione o que você utiliza por dia");

        chuveiro.setText("Chuveiro");
        chuveiro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chuveiroItemStateChanged(evt);
            }
        });
        chuveiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuveiroActionPerformed(evt);
            }
        });

        Descarga.setText("Privada");
        Descarga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DescargaItemStateChanged(evt);
            }
        });

        PiaBanheiro.setText("Pia do banheiro");
        PiaBanheiro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PiaBanheiroItemStateChanged(evt);
            }
        });

        maquinaRoupa.setText("Maquina de lavar roupa");
        maquinaRoupa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maquinaRoupaItemStateChanged(evt);
            }
        });

        tanqueRoupa.setText("Tanque de lavar roupa");
        tanqueRoupa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tanqueRoupaItemStateChanged(evt);
            }
        });

        piaCozinha.setText("Pia da cozinha");
        piaCozinha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                piaCozinhaItemStateChanged(evt);
            }
        });

        maquinaLouca.setText("Maquina de lavar louça");
        maquinaLouca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maquinaLoucaItemStateChanged(evt);
            }
        });

        Proximo.setText("Próximo");
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoActionPerformed(evt);
            }
        });

        tempVez.setText("Tempo/Vezes");

        lblCasa.setText("Min");

        lblPrivada.setText("Vezes");

        lblPiaB.setText("Min");

        lblmaquiR.setText("Vezes");

        lbltanque.setText("Min");

        lblPiaC.setText("Min");

        lblmaquiL.setText("Vezes");

        Casa.setText("Casa");
        Casa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CasaItemStateChanged(evt);
            }
        });

        Ap.setText("Apartemento");
        Ap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ApItemStateChanged(evt);
            }
        });

        lblAp.setText("Min");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Casa)
                            .addComponent(lblPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTcasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCasa))
                            .addComponent(JSpessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTap, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAp))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(Proximo)
                                        .addGap(85, 85, 85))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Descarga)
                                            .addComponent(PiaBanheiro)
                                            .addComponent(maquinaRoupa)
                                            .addComponent(tanqueRoupa)
                                            .addComponent(piaCozinha)
                                            .addComponent(maquinaLouca))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTpiaC)
                                            .addComponent(JTtanque)
                                            .addComponent(JTpiaB)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(JTmaquiL, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JTmaquiR, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                    .addComponent(JTprivada))
                                                .addGap(12, 12, 12)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblmaquiL)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblPrivada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPiaB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblmaquiR, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPiaC, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbltanque, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chuveiro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Selecione)
                                        .addGap(18, 18, 18)
                                        .addComponent(tempVez)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Selecione)
                    .addComponent(tempVez))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chuveiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Casa)
                            .addComponent(JTcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ap)
                            .addComponent(lblAp)
                            .addComponent(JTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JSpessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descarga)
                    .addComponent(JTprivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrivada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PiaBanheiro)
                    .addComponent(JTpiaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPiaB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maquinaRoupa)
                    .addComponent(JTmaquiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmaquiR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanqueRoupa)
                    .addComponent(JTtanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltanque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piaCozinha)
                    .addComponent(JTpiaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPiaC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maquinaLouca)
                    .addComponent(JTmaquiL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmaquiL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Proximo)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chuveiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuveiroActionPerformed
        
    }//GEN-LAST:event_chuveiroActionPerformed

    private void ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoActionPerformed
        DecimalFormat df = new DecimalFormat("#00.00"); // restringe as variaveis double para 2 casas
        teste2 form = new teste2(); // instancia o Jframe2
        // criação de variaveis para gerenciar o valor de litros gastos em cada um
        double Chuv = 0;
        double Desc = 0;
        double PiaB = 0;
        double MaquiR = 0;
        double Tanq = 0;
        double MaquiL = 0;
        double PiaC = 0;
        //verificação para habilitar a escrita dos objetos
        if(chuveiro.isSelected()){
            if(Casa.isSelected()){
                Chuv = Integer.parseInt(JTcasa.getText())*3*7*4;//calculo se morar em casa
            } else{
                Chuv = Integer.parseInt(JTap.getText())*9.6*7*4;// calculo se morar em AP
            }
            form.Chuv();//faz aparecer no Jframe2 o campo chuveiro
        }
        if(Descarga.isSelected()){
            form.Desc();//faz aparecer no Jframe2 o campo privada/descarga
            Desc = Integer.parseInt(JTprivada.getValue().toString())*10*7*4;
        }
        if(PiaBanheiro.isSelected()){
            form.PiaBanho();//faz aparecer no Jframe2 o campo pia do banheiro
            PiaB = Integer.parseInt(JTpiaB.getText())*9*7*4;
        }
        if(maquinaRoupa.isSelected()){
            form.MaquiR();//faz aparecer no Jframe2 o campo maquina de lavar roupa
            MaquiR = Integer.parseInt(JTmaquiL.getValue().toString())*135*7*4;
        }
        if(tanqueRoupa.isSelected()){
            form.Tanque();//faz aparecer no Jframe2 o campo tanque
            Tanq = Integer.parseInt(JTtanque.getText())*18.6*7*4;
        }
        if(piaCozinha.isSelected()){
            form.PiaCoz();//faz aparecer no Jframe2 o campo pia da cozinha
            PiaC = Integer.parseInt(JTpiaC.getText())*7.8*7*4;
        }
        if(maquinaLouca.isSelected()){
            form.MaquiL();//faz aparecer no Jframe2 o campo maquina de louça
            MaquiL = Integer.parseInt(JTmaquiL.getValue().toString())*40*7*4;
        }
        double total = Chuv + Tanq + Desc + MaquiL + MaquiR + PiaB + PiaC; // calculo do total de Litros gastos
        double TotalM = total/1000;//total de m³ gastos
        //envia o valor do gasto de cada objeto;
        form.setLblChuveiro(df.format(Chuv));
        form.setLbltanque(df.format(Tanq));
        form.setLbldescarga(df.format(Desc));
        form.setLblmaquiL(df.format(MaquiL));
        form.setLblmaquiR(df.format(MaquiR));
        form.setLblpiaB(df.format(PiaB));
        form.setLblpiaC(df.format(PiaC));
        form.setLblTotal(df.format(total));
        form.setLbltotalM(Double.toString(TotalM));
        form.setVisible(true);//habilita a visualização do JFrame2
    }//GEN-LAST:event_ProximoActionPerformed

    /*
        Apartir desta parte são metodos gerados pelo prorpio nebeans. Que possiblita a mudança de algo se ocorer alguma moddficação na checkBox.
        Isso permitiu que eu pudesse dar mais interação com o usuario fazendo aparecer e desaparecer os campos de digitação.
    
        setVisible é o comando que permite essa aparição do campo de texto.
    */
    
    private void chuveiroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chuveiroItemStateChanged
        if(chuveiro.isSelected()){
            Ap.setVisible(true);
            Casa.setVisible(true);
        }else{
            Ap.setVisible(false);
            Casa.setVisible(false);
        }
    }//GEN-LAST:event_chuveiroItemStateChanged

    private void DescargaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DescargaItemStateChanged
        if(Descarga.isSelected()){
            JTprivada.setVisible(true);
            lblPrivada.setVisible(true);
        }else{
            JTprivada.setVisible(true);
            lblPrivada.setVisible(true);
        }
    }//GEN-LAST:event_DescargaItemStateChanged

    private void PiaBanheiroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PiaBanheiroItemStateChanged
        if(PiaBanheiro.isSelected()){
            JTpiaB.setVisible(true);
            lblPiaB.setVisible(true);
        }else{
            JTpiaB.setVisible(false);
            lblPiaB.setVisible(false);
        }
    }//GEN-LAST:event_PiaBanheiroItemStateChanged

    private void maquinaRoupaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maquinaRoupaItemStateChanged
        if(maquinaRoupa.isSelected()){
            JTmaquiR.setVisible(true);
            lblmaquiR.setVisible(true);
        }else{
            JTmaquiR.setVisible(true);
            lblmaquiR.setVisible(true);
        }
    }//GEN-LAST:event_maquinaRoupaItemStateChanged

    private void tanqueRoupaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tanqueRoupaItemStateChanged
        if(tanqueRoupa.isSelected()){
            JTtanque.setVisible(true);
            lbltanque.setVisible(true);
        }else{
            JTtanque.setVisible(false);
            lbltanque.setVisible(false);
        }
    }//GEN-LAST:event_tanqueRoupaItemStateChanged

    private void piaCozinhaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_piaCozinhaItemStateChanged
        if(piaCozinha.isSelected()){
            JTpiaC.setVisible(true);
            lblPiaC.setVisible(true);
        }else{
            JTpiaC.setVisible(false);
            lblPiaC.setVisible(false);
        }
    }//GEN-LAST:event_piaCozinhaItemStateChanged

    private void maquinaLoucaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maquinaLoucaItemStateChanged
        if(maquinaLouca.isSelected()){
            JTmaquiL.setVisible(true);
            lblmaquiL.setVisible(true);
        }else{
            JTmaquiL.setVisible(false);
            lblmaquiL.setVisible(false);
        }
    }//GEN-LAST:event_maquinaLoucaItemStateChanged

    private void CasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CasaItemStateChanged
        if(Casa.isSelected()){
            JTcasa.setVisible(true);
            lblCasa.setVisible(true);
            lblPessoas.setVisible(true);
            lblPessoas.setText("Quantas pessoas na Casa");
            JSpessoas.setVisible(true);
        }else{
            JTcasa.setVisible(false);
            lblCasa.setVisible(false);
            lblPessoas.setVisible(false);
            JSpessoas.setVisible(false);
        }
    }//GEN-LAST:event_CasaItemStateChanged

    private void ApItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ApItemStateChanged
        if(Ap.isSelected()){
            JTap.setVisible(true);
            lblAp.setVisible(true);
            lblPessoas.setVisible(true);
            lblPessoas.setText("Quantas pessoas no AP");
            JSpessoas.setVisible(true);
        }else{
            JTap.setVisible(false);
            lblAp.setVisible(false);
            lblPessoas.setVisible(false);
            JSpessoas.setVisible(false);
        }
    }//GEN-LAST:event_ApItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ap;
    private javax.swing.JCheckBox Casa;
    private javax.swing.JCheckBox Descarga;
    private javax.swing.JSpinner JSpessoas;
    private javax.swing.JTextField JTap;
    private javax.swing.JTextField JTcasa;
    private javax.swing.JSpinner JTmaquiL;
    private javax.swing.JSpinner JTmaquiR;
    private javax.swing.JTextField JTpiaB;
    private javax.swing.JTextField JTpiaC;
    private javax.swing.JSpinner JTprivada;
    private javax.swing.JTextField JTtanque;
    private javax.swing.JCheckBox PiaBanheiro;
    private javax.swing.JButton Proximo;
    private javax.swing.JLabel Selecione;
    private javax.swing.JCheckBox chuveiro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAp;
    private javax.swing.JLabel lblCasa;
    private javax.swing.JLabel lblPessoas;
    private javax.swing.JLabel lblPiaB;
    private javax.swing.JLabel lblPiaC;
    private javax.swing.JLabel lblPrivada;
    private javax.swing.JLabel lblmaquiL;
    private javax.swing.JLabel lblmaquiR;
    private javax.swing.JLabel lbltanque;
    private javax.swing.JCheckBox maquinaLouca;
    private javax.swing.JCheckBox maquinaRoupa;
    private javax.swing.JCheckBox piaCozinha;
    private javax.swing.JCheckBox tanqueRoupa;
    private javax.swing.JLabel tempVez;
    // End of variables declaration//GEN-END:variables
}
